[project]
name = "mcp-ctera-edge"
version = "0.1.0"
description = "An MCP Server for interacting with CTERA Edge Filer"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cterasdk>=2.20.10",
    "fastapi[standard]>=0.115.12",
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.3",
]
